name: Publish container images to ghcr
on:
   push
jobs:
   build_and_publish:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Build & Push image
           run: |
              docker login --username rdev2021 --password ${{ secrets.GH_PATH }} ghcr.io
              docker build . --tag ghcr.io/rdev2021/network-test:latest
              docker push ghcr.io/rdev2021/network-test:latest
